resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config.yaml
- rbac.yaml
- ingress.yaml
commonLabels:
  owner: tommylike
  app: covid-shanghai-server
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: covid-shanghai

